[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file=["requirements.txt"]}

[tool.setuptools]
packages = [
    "converters"
]

[project]
name = "converters"
version = "26.0.0"
description = "Arras Energy converters for GridLAB-D"
authors = [
    {name = "David P. Chassin <dchassin@eudoxys.com>"},
    ]
maintainers = [
    {name = "David P. Chassin <dchassin@eudoxys.com>"},
    ]
readme = "README.md"
requires-python = "== 3.10.*"
keywords = ["github","python","arras","converters","gridlabd"]
license = {text="MIT License"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    ]
dynamic=["dependencies"]

[project.urls]
Homepage = "https://github.com/arras-energy/converters"
Documentation = "https://arras.energy/converters"
Repository = "https://github.com/arras-energy/converters.git"
Issues = "https://github.com/arras-energy/converters/issues"
